Repository jamjam-book/be15-2nd-jamjam-bookjeok, pull requests merged in 2025-04, with the labels that each got.

#5 docs : README 생성 및 커밋 메시지 규칙 추가
  README.md
Labels: 📝 문서

#4 chore: 이슈 공통 템플릿 생성 완료
  .github/ISSUE_TEMPLATE/이슈-공통-템플릿.md
Labels: 🗃️ 템플릿

#6 feat: 애플리케이션 설정 파일에 api key, mybatis type-aliases-package 추가
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🤖 기능

#7 ci: main 브랜치 PR 시 테스트 실행을 위한 GitHub Actions 워크플로우 추가
  .github/workflows/ci.yml
Labels: ci/cd

#10 feat: member엔터티와 follow 엔터티 생성
  src/main/java/com/jamjam/bookjeok/domains/member/entity/Follow.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/Member.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/MemberRole.java
Labels: 🤖 기능

#11 feat: 관심도서, 관심저자, 이메일 전송 내역 entity 생성 완료
  src/main/java/com/jamjam/bookjeok/domains/member/entity/InterestAuthors.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/InterestBooks.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/SendingEmailHistories.java
Labels: 🤖 기능

#14 [FEAT] 도서 , CS 관련 Entity 생성
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Author.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookCategory.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Publisher.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/StockNotification.java
  src/main/java/com/jamjam/bookjeok/domains/notice/entity/Notice.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/Question.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionCategory.java
Labels: 🤖 기능

#43 [FIX] Validate PR with Tests 기능 비활성화
  .github/workflows/ci.yml
Labels: ci/cd

#44 [FEAT] 도서 정보 연동 API 구현
  build.gradle
  src/main/java/com/jamjam/bookjeok/domains/book/contoller/BookApiController.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookApiDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/NaverResultDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/BookRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiService.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookCommandService.java
Labels: 🤖 기능

#47 [REFACTOR] 주문, 결제 엔티티 연관관계 제거 및 id명을 명확하게 변경
  src/main/java/com/jamjam/bookjeok/domains/order/entity/Cart.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/Order.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/OrderDetail.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/OrderStatus.java
  src/main/java/com/jamjam/bookjeok/domains/payment/entity/Payment.java
Labels: 🔨 수정

#46 [REFACTOR] 쿠폰, 포인트, 배송 관련 엔티티 수정
  src/main/java/com/jamjam/bookjeok/domains/coupon/entity/Coupon.java
  src/main/java/com/jamjam/bookjeok/domains/coupon/entity/CouponBox.java
  src/main/java/com/jamjam/bookjeok/domains/coupon/entity/DiscountType.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/DeliveryAddress.java
  src/main/java/com/jamjam/bookjeok/domains/point/entity/Point.java
  src/main/java/com/jamjam/bookjeok/domains/point/entity/PointType.java
  src/test/resources/application-test.yml
Labels: ♻️ 리팩토링

#45 [REFACTOR] 도서, 공지사항, 문의사항 관련 엔터티 연관관계 수정
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Author.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookCategory.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Publisher.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionCategory.java
Labels: ♻️ 리팩토링

#48 [REFACTOR] 커뮤니티 게시글, 댓글, 즐겨찾기, 좋아요, 신고 기능 엔티티 연관관계 제거 및 아이디명 변경
  src/main/java/com/jamjam/bookjeok/domains/community/entity/Bookmark.java
  src/main/java/com/jamjam/bookjeok/domains/community/entity/Comment.java
  src/main/java/com/jamjam/bookjeok/domains/community/entity/Like.java
  src/main/java/com/jamjam/bookjeok/domains/community/entity/Post.java
  src/main/java/com/jamjam/bookjeok/domains/community/entity/Report.java
Labels: ♻️ 리팩토링

#49 [REFACTOR]: 도서, 공지사항, 문의사항 엔터티 연관관계 및 제약조건 수정
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/StockNotification.java
  src/main/java/com/jamjam/bookjeok/domains/notice/entity/Notice.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/Question.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionAnswer.java
Labels: ♻️ 리팩토링

#56 [FEATURE] 장바구니에 도서 정보를 등록하는 로직 구현
  src/main/java/com/jamjam/bookjeok/domains/order/controller/cart/CartController.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/request/CartRequest.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/response/CartResponse.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/Cart.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/CartRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/order/cart/CartExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/order/cart/CartItemLimitExceededException.java
  src/main/resources/mappers/domain/order/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/BookjeokApplicationTests.java
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/entity/CartTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: 🤖 기능

#55 [CI] main 브랜치 PR 시 테스트 실행을 위한 GitHub Actions 워크플로우 삭제
  .github/workflows/ci.yml
  src/test/resources/application-test.yml
Labels: ci/cd

#57 [FEATURE] 장바구니에 있는 도서 수량을 변경하는 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/order/controller/cart/CartController.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/Cart.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/order/cart/CartBookNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/order/cart/CartExceptionHandler.java
  src/main/resources/mappers/domain/order/cart/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: 🤖 기능

#59 [REFACTOR] CartBookNotFoundException 예외 메시지 변경
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: 🔨 수정

#58 [FEAT] Book Entity, BookAuthor Entity 변경
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookAuthor.java
Labels: 🤖 기능

#62 [FEATURE] memberUid로 장바구니에 있는 도서 정보를 조회하는 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/order/controller/cart/CartController.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/request/CartMemberIdRequest.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/response/CartBookListResponse.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/response/CartBookResponse.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/main/resources/mappers/domain/order/cart/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: 🤖 기능

#63 [FEATURE] mybatis 로그 출력 설정 및 이미지 경로 설정 추가
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🤖 기능

#65 [FEATURE] OrderDetail 엔티티 수정
  src/main/java/com/jamjam/bookjeok/domains/order/entity/OrderDetail.java
Labels: 🔨 수정, 🤖 기능

#64 [FEATURE] 도서 API 연동 구현하기
  src/main/java/com/jamjam/bookjeok/domains/book/contoller/BookApiController.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/AuthorDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookApiDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookAuthorDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookCategoryDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/NaverResultDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/PublisherDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Book.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/BookCategory.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/AuthorRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/BookAuthorRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/BookCategoryRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/BookRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/PublisherRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiService.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/book/BookExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/book/BookNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/book/FileStorageException.java
  src/main/java/com/jamjam/bookjeok/exception/book/RegistPreexistingBookException.java
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookApiControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImplTest.java
Labels: 🤖 기능

#66 [BUILD] Apache Commons IO 라이브러리 추가
  build.gradle
Labels: ⚙ 세팅

#68 [FEAT] 회원의 id로 팔로우 목록 조회하는 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/FollowController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/FollowDTO.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/FollowMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/FollowService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberException.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  src/main/resources/mappers/member/FollowMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/FollowControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/FollowMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/FollowServiceTest.java
Labels: 🤖 기능

#69 [REFACTOR] Builder import 및 mapper에서 컬럼명 수정
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/FollowDTO.java
  src/main/resources/mappers/member/FollowMapper.xml
Labels: ♻️ 리팩토링

#70 [FEAT] 팔로우 하는 회원의 게시글 목록 보기 기능 완료
  src/main/java/com/jamjam/bookjeok/domains/member/controller/FollowController.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/FollowMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/FollowService.java
  src/main/resources/mappers/member/FollowMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/FollowControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/FollowMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/FollowServiceTest.java
Labels: 🤖 기능

#72 [FEAT] 특정 회원의 관심 작가와 그 작가의 책 목록 가져오기
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/BookNameDTO.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestAuthorDTO.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorService.java
  src/main/resources/mappers/member/InterestAuthorMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
Labels: 🤖 기능

#75 [REFACTOR] 클라이언트가 서버에 도서 가격을 전달하지 않도록 코드 수정
  src/main/java/com/jamjam/bookjeok/domains/order/dto/cart/request/CartRequest.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/main/resources/mappers/domain/order/cart/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: 🔨 수정

#73 [CHORE] books.controller 패키지명 변경
  src/main/java/com/jamjam/bookjeok/domains/book/controller/BookApiController.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookCategoryDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDTO.java
Labels: 🔨 수정

#77 [FEAT] 관심 작가 추가하기
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestAuthorCreatRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/InterestAuthorResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/InterestAuthor.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/InterestAuthorRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestAuthorException/AlreadyInterestedAuthorException.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestAuthorException/AuthorNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestAuthorException/InterestAuthorLimitExceededException.java
  src/main/resources/mappers/member/InterestAuthorMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
Labels: 🤖 기능

#78 [REFACTOR] BookApiController EndPoint 변경 및 파일 저장 변경
  src/main/java/com/jamjam/bookjeok/domains/book/controller/BookApiController.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiService.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookCommandService.java
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookApiControllerTest.java
Labels: ♻️ 리팩토링

#81 [REFACTOR] API 데이터 저장 메소드 분리 및 카테고리 저장 값 변경
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImpl.java
Labels: ♻️ 리팩토링

#80 [FEATURE] 관심 작가 삭제 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestAuthorRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/InterestAuthorRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestAuthorMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
Labels: 🤖 기능

#83 [FEATURE] 결제 요청 시 주문 정보를 임시 주문 내역 테이블에 저장하는 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderController.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/request/PendingOrderBookItemsRequest.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/request/PendingOrderRequest.java
  src/main/java/com/jamjam/bookjeok/domains/order/dto/pendingorder/response/PendingOrderResponse.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/PendingOrder.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/order/pendingorder/PendingOrderRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImpl.java
  src/test/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/entity/PendingOrderTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImplTest.java
Labels: 🤖 기능

#86 [FEATURE] 회원 전체 목록 조회 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/PageRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/MemberListResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/AdminService.java
  src/main/resources/mappers/member/AdminMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/AdminControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/AdminServiceTest.java
Labels: 🤖 기능

#87 [TEST] 더미 데이터 변경에 따른 테스트 코드 수정
  src/main/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapper.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImpl.java
  src/main/resources/mappers/domain/order/cart/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/order/controller/cart/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/repository/cart/mapper/CartMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/cart/CartServiceImplTest.java
Labels: ✔️ 테스트

#88 [REFACTOR] 불필요한 import 제거 및 누락된 DTO 추가
  src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/MemberDTO.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/AdminService.java
  src/test/java/com/jamjam/bookjeok/domains/member/controller/AdminControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/AdminServiceTest.java
Labels: ♻️ 리팩토링

#89 [TEST] 새로운 더미 데이터에 맞게 InterestAuthorController 테스트 수정
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestAuthorControllerTest.java
Labels: ✔️ 테스트

#90 [FEAT] 특정 회원의 관심 도서 목록 가져오기
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestBookController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestBookDTO.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestBookRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/InterestBookListResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestBookService.java
  src/main/resources/mappers/member/InterestBookMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestBookControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestBookServiceTest.java
Labels: 🤖 기능

#91 [REFACTOR] tosspayments.api-secret-key 오타 수정
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ⚙ 세팅

#92 [FEATURE] 일반회원 도서 조회 및 구매 도서 리뷰 등록, 조회, 수정, 삭제 기능 개발
  src/main/java/com/jamjam/bookjeok/domains/book/controller/BookMemberController.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDetailDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/BookDetailPageDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/PopularBookDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/ReviewDTO.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/request/ReviewRequest.java
  src/main/java/com/jamjam/bookjeok/domains/book/dto/response/ReviewResponse.java
  src/main/java/com/jamjam/bookjeok/domains/book/entity/Review.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/ReviewRepository.java
  src/main/java/com/jamjam/bookjeok/domains/book/repository/mapper/BookMapper.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookMemberService.java
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookMemberServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/book/BookErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/book/BookExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/book/review/InconsistentReviewException.java
  src/main/java/com/jamjam/bookjeok/exception/book/review/ReviewNotFoundException.java
  src/main/resources/mappers/book/BookMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookMemberControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/book/mapper/BookMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/book/service/BookMemberServiceImplTest.java
Labels: 🤖 기능

#94 [FEATURE] 팔로우 하기 기능 구현하기
  src/main/java/com/jamjam/bookjeok/domains/member/controller/FollowController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/FollowMemberRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/FollowMemberResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/Follow.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/FollowRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/MemberRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/FollowService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/member/followException/AlreadyFollowException.java
  src/main/resources/mappers/member/FollowMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/FollowControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/FollowMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/FollowServiceTest.java
Labels: 🤖 기능

#95 [REFACTOR] Category Exception 패키지 구조 변경
  src/main/java/com/jamjam/bookjeok/exception/book/category/BookCategoryNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/book/category/RegistPreexistingCategoryException.java
Labels: ♻️ 리팩토링

#96 [FEAT] 멤버의 아이디나 닉네임으로 멤버 검색하는 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/MemberSearchRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/MemberDetailResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/AdminService.java
  src/main/resources/mappers/member/AdminMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/AdminControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/AdminMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/AdminServiceTest.java
Labels: 🤖 기능

#97 [REFACTOR] BookAdminServiceImpl 누락된 내용 추가
  src/main/java/com/jamjam/bookjeok/domains/book/service/BookAdminServiceImpl.java
Labels: ♻️ 리팩토링

#98 [REFACTOR] BookAdminServiceImplTest 누락된 내용 추가
  src/test/java/com/jamjam/bookjeok/domains/book/service/BookAdminServiceImplTest.java
Labels: ♻️ 리팩토링

#100 [FEAT] 팔로우 삭제 기능 구현하기
  src/main/java/com/jamjam/bookjeok/domains/member/controller/FollowController.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/FollowRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/FollowService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/member/followException/NotFollowException.java
  src/test/java/com/jamjam/bookjeok/domains/member/controller/FollowControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/FollowServiceTest.java
Labels: 🤖 기능

#101 [REFACTOR] 필요 없는 import 삭제하기
  src/main/java/com/jamjam/bookjeok/domains/member/dto/InterestAuthorDTO.java
Labels: ♻️ 리팩토링

#102 [FEATURE] 관리자 문의사항 조회, 답변 등록, 답변 수정, 답변 삭제 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/question/controller/QuestionAdminController.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/QuestionDTO.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/QuestionListDTO.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/request/QuestionAnswerRequest.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/response/QuestionAnswerResponse.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/QuestionAnswer.java
  src/main/java/com/jamjam/bookjeok/domains/question/repository/QuestionAnswerRepository.java
  src/main/java/com/jamjam/bookjeok/domains/question/repository/mapper/QuestionMapper.java
  src/main/java/com/jamjam/bookjeok/domains/question/service/QuestionAdminService.java
  src/main/java/com/jamjam/bookjeok/domains/question/service/QuestionAdminServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/question/InconsistentQuestionException.java
  src/main/java/com/jamjam/bookjeok/exception/question/NotFoundQuestionException.java
  src/main/java/com/jamjam/bookjeok/exception/question/QuestionErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/question/QuestionExceptionHandler.java
  src/main/resources/mappers/question/QuestionMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/question/controller/QuestionAdminControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/question/mapper/QuestionMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionAdminServiceTest.java
Labels: 🤖 기능

#105 [FEAT] 관심 도서 추가 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestBookController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/InterestBookRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/response/InterestBookResponse.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/InterestBook.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/repository/InterestBookRepository.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestBookService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestBookException/AlreadyInterestedBookException.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestBookException/InterestBookLimitExceededException.java
  src/main/java/com/jamjam/bookjeok/exception/member/interestBookException/NotFoundBookException.java
  src/main/resources/mappers/member/InterestBookMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestBookControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/repository/mapper/InterestBookMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestBookServiceTest.java
Labels: 🤖 기능

#106 [FEAT] 관심 도서 삭제 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/member/controller/InterestBookController.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/InterestBookService.java
  src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  src/test/java/com/jamjam/bookjeok/domains/member/controller/InterestBookControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestBookServiceTest.java
Labels: 🤖 기능

#107 [REFACTOR] 필요 없는 import 제거
  src/test/java/com/jamjam/bookjeok/domains/member/service/InterestAuthorServiceTest.java
Labels: ♻️ 리팩토링

#108 [FEATURE] 회원 문의사항 조회, 등록, 수정, 삭제 기능 개발
  src/main/java/com/jamjam/bookjeok/domains/question/controller/QuestionMemberController.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/QuestionCategoryDTO.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/request/QuestionRequest.java
  src/main/java/com/jamjam/bookjeok/domains/question/dto/response/QuestionResponse.java
  src/main/java/com/jamjam/bookjeok/domains/question/entity/Question.java
  src/main/java/com/jamjam/bookjeok/domains/question/repository/QuestionAnswerRepository.java
  src/main/java/com/jamjam/bookjeok/domains/question/repository/QuestionRepository.java
  src/main/java/com/jamjam/bookjeok/domains/question/repository/mapper/QuestionMapper.java
  src/main/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberService.java
  src/main/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/question/QuestionErrorCode.java
  src/main/resources/mappers/question/QuestionMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/question/controller/QuestionMemberControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/question/mapper/QuestionMapperTest.java
  src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceTest.java
Labels: 🤖 기능

#109 [TEST] 도서 API Service 및 도서 리뷰 Controller TEST를 위한 코드 수정
  src/main/java/com/jamjam/bookjeok/domains/book/controller/BookMemberController.java
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookMemberControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/book/service/BookApiServiceImplTest.java
Labels: 🐞 버그, ✔️ 테스트

#111 [FEATURE] tosspayments api를 연동해서 주문-결제 기능 구현
  src/main/java/com/jamjam/bookjeok/domains/order/dto/orderdetail/OrderDetailDTO.java
  src/main/java/com/jamjam/bookjeok/domains/order/entity/Order.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/order/OrderRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/order/pendingorder/PendingOrderRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/orderdetail/OrderDetailRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/orderdetail/mapper/OrderDetailMapper.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/orderdetail/OrderDetailService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/orderdetail/OrderDetailServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/controller/PaymentController.java
  src/main/java/com/jamjam/bookjeok/domains/payment/controller/TossPaymentTestController.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/BookInventoryDTO.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/OrderItemsDTO.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/PaymentDTO.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/PendingOrderDTO.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/com/jamjam/bookjeok/domains/payment/infrastructure/service/TossPaymentService.java
  src/main/java/com/jamjam/bookjeok/domains/payment/infrastructure/service/TossPaymentServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/repository/PaymentRepository.java
  src/main/java/com/jamjam/bookjeok/domains/payment/repository/mapper/PaymentMapper.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentService.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/order/orderdetail/OrderDetailExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/order/orderdetail/OrderDetailNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/payment/BookInfoNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/payment/ExternalPaymentException.java
  src/main/java/com/jamjam/bookjeok/exception/payment/InsufficientBookStockException.java
  src/main/java/com/jamjam/bookjeok/exception/payment/PaymentExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/payment/PaymentOrderNotFountException.java
  src/main/resources/mappers/domain/order/orderdetail/OrderDetailMapper.xml
  src/main/resources/mappers/payment/Payment.xml
Labels: 🤖 기능

#110 [TEST] 회원 문의사항 수정 테스트 카테고리 ID값 수정
  src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceTest.java
Labels: ✔️ 테스트

#112 [REFACTOR] mapper.xml 파일 위치 변경
  src/main/resources/mappers/order/cart/CartMapper.xml
  src/main/resources/mappers/order/orderdetail/OrderDetailMapper.xml
Labels: ♻️ 리팩토링

#113 [TEST] api 호출 제한 수 초과 방지를 위한 테스트 삭제
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookApiControllerTest.java
Labels: ✔️ 테스트

#114 [TEST] 문의사항 수정 테스트 questionId 값 변경
  src/test/java/com/jamjam/bookjeok/domains/question/controller/QuestionMemberControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/question/service/QuestionMemberServiceTest.java
Labels: ✔️ 테스트

#115 [FEATURE] 구매할 도서 재고 수량이 충분한 경우 재고 수량을 감소시키는 로직 추가
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/BookInventoryDTO.java
  src/main/java/com/jamjam/bookjeok/domains/payment/repository/mapper/PaymentMapper.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java
  src/main/resources/mappers/payment/Payment.xml
Labels: 🤖 기능

#117 [TEST] 회원 리뷰 자격 증명 테스트 결과 비교 값 변경
  src/main/java/com/jamjam/bookjeok/domains/book/controller/BookMemberController.java
  src/test/java/com/jamjam/bookjeok/domains/book/controller/BookMemberControllerTest.java
Labels: ✔️ 테스트

#118 [REFACTOR] 결제 로직에서 책임 분리를 위한 서비스 의존성 리팩토링
  src/main/java/com/jamjam/bookjeok/domains/order/entity/PendingOrder.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/orderdetail/OrderDetailRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/order/OrderService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/order/OrderServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/orderdetail/OrderDetailService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/orderdetail/OrderDetailServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/repository/mapper/PaymentMapper.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java
  src/main/resources/mappers/payment/Payment.xml
  src/test/java/com/jamjam/bookjeok/domains/order/service/orderdetail/OrderDetailServiceImplTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImplTest.java
Labels: ♻️ 리팩토링

#119 [FEATURE] : 회원가입, 로그인, 로그아웃, 리프레시토큰재발급 기능 추가
  build.gradle
  src/main/java/com/jamjam/bookjeok/auth/controller/AuthController.java
  src/main/java/com/jamjam/bookjeok/auth/dto/LoginRequest.java
  src/main/java/com/jamjam/bookjeok/auth/dto/RefreshTokenRequest.java
  src/main/java/com/jamjam/bookjeok/auth/dto/TokenResponse.java
  src/main/java/com/jamjam/bookjeok/auth/entity/RefreshToken.java
  src/main/java/com/jamjam/bookjeok/auth/repository/RefreshTokenRepository.java
  src/main/java/com/jamjam/bookjeok/auth/service/AuthService.java
  src/main/java/com/jamjam/bookjeok/auth/service/CustomUserDetailsService.java
  src/main/java/com/jamjam/bookjeok/config/SecurityConfig.java
  src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java
  src/main/java/com/jamjam/bookjeok/domains/member/controller/MemberCommandController.java
  src/main/java/com/jamjam/bookjeok/domains/member/controller/MemberQueryController.java
  src/main/java/com/jamjam/bookjeok/domains/member/dto/request/MemberCreateRequest.java
  src/main/java/com/jamjam/bookjeok/domains/member/entity/Member.java
  src/main/java/com/jamjam/bookjeok/domains/member/repository/mapper/MemberMapper.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/MemberCommandService.java
  src/main/java/com/jamjam/bookjeok/domains/member/service/MemberQueryService.java
  src/main/java/com/jamjam/bookjeok/jwt/JwtAuthenticationFilter.java
  src/main/java/com/jamjam/bookjeok/jwt/JwtTokenProvider.java
  src/main/java/com/jamjam/bookjeok/jwt/RestAccessDeniedHandler.java
  src/main/java/com/jamjam/bookjeok/jwt/RestAuthenticationEntryPoint.java
  src/main/resources/application.yml
  src/main/resources/mappers/member/MemberMapper.xml
  src/test/resources/application-test.yml
Labels: 🤖 기능

#122 [DOCS] README.md 주문 테스트 위치 수정
  README.md
Labels: 📝 문서

#123 docs : 리드미 목차 추가하기
  README.md
Labels: 📝 문서

#125 [FIX] 도서 재고 수량이 부족한 경우 임시 주문 정보 삭제가 안되는 부분 수정
  src/main/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderController.java
  src/main/java/com/jamjam/bookjeok/domains/order/repository/order/pendingorder/PendingOrderRepository.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java
  src/test/java/com/jamjam/bookjeok/domains/order/controller/order/PendingOrderControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/order/service/pendingorder/PendingOrderServiceImplTest.java
Labels: 🐞 버그, 🔨 수정

#126 [REFACTOR] 장바구니 관련 기능들을 order 패키지에서 분리하여 cart 패키지로 이동
  src/main/java/com/jamjam/bookjeok/domains/cart/controller/CartController.java
  src/main/java/com/jamjam/bookjeok/domains/cart/dto/request/CartMemberIdRequest.java
  src/main/java/com/jamjam/bookjeok/domains/cart/dto/request/CartRequest.java
  src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartBookListResponse.java
  src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartBookResponse.java
  src/main/java/com/jamjam/bookjeok/domains/cart/dto/response/CartResponse.java
  src/main/java/com/jamjam/bookjeok/domains/cart/entity/Cart.java
  src/main/java/com/jamjam/bookjeok/domains/cart/repository/CartRepository.java
  src/main/java/com/jamjam/bookjeok/domains/cart/repository/mapper/CartMapper.java
  src/main/java/com/jamjam/bookjeok/domains/cart/service/CartService.java
  src/main/java/com/jamjam/bookjeok/domains/cart/service/CartServiceImpl.java
  src/main/java/com/jamjam/bookjeok/exception/cart/CartBookNotFoundException.java
  src/main/java/com/jamjam/bookjeok/exception/cart/CartExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/cart/CartItemLimitExceededException.java
  src/main/resources/mappers/order/cart/CartMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/cart/controller/CartControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/cart/entity/CartTest.java
  src/test/java/com/jamjam/bookjeok/domains/cart/service/CartServiceImplTest.java
Labels: ♻️ 리팩토링

#127 [REFACTOR] 임시 주문 관련 기능들을 order 패키지에서 분리하여 pendingorder 패키지로 이동
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/PendingOrderDTO.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/controller/PendingOrderController.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/dto/request/PendingOrderBookItemsRequest.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/dto/request/PendingOrderRequest.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/dto/response/PendingOrderResponse.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/entity/PendingOrder.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/repository/PendingOrderRepository.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/service/PendingOrderService.java
  src/main/java/com/jamjam/bookjeok/domains/pendingorder/service/PendingOrderServiceImpl.java
  src/test/java/com/jamjam/bookjeok/domains/pendingorder/controller/PendingOrderControllerTest.java
  src/test/java/com/jamjam/bookjeok/domains/pendingorder/entity/PendingOrderTest.java
  src/test/java/com/jamjam/bookjeok/domains/pendingorder/service/PendingOrderServiceImplTest.java
Labels: ♻️ 리팩토링

#129 [REFACTOR] 주문 상세 내역 관련 기능들을 order 패키지에서 분리하여 orderdetail 패키지로 이동
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/dto/OrderDetailDTO.java
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/entity/OrderDetail.java
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/repository/OrderDetailRepository.java
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/repository/mapper/OrderDetailMapper.java
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailService.java
  src/main/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/OrderItemsDTO.java
  src/main/java/com/jamjam/bookjeok/exception/orderdetail/OrderDetailExceptionHandler.java
  src/main/java/com/jamjam/bookjeok/exception/orderdetail/OrderDetailNotFoundException.java
  src/main/resources/mappers/order/orderdetail/OrderDetailMapper.xml
  src/test/java/com/jamjam/bookjeok/domains/orderdetail/service/OrderDetailServiceImplTest.java
Labels: ♻️ 리팩토링

#131 [FIX] admin인 경우에만 멤버를 검색, 조회할 수 있게 수정 및 controller테스트 수정
  src/main/java/com/jamjam/bookjeok/domains/member/controller/AdminController.java
  src/main/java/com/jamjam/bookjeok/domains/member/controller/MemberQueryController.java
  src/test/java/com/jamjam/bookjeok/domains/member/controller/AdminControllerTest.java
Labels: ✔️ 테스트, 🔨 수정

#132 [REFACTOR] pendingorder, orderdetail 패키지 구조 변경에 따른 import 경로 수정
  src/main/java/com/jamjam/bookjeok/domains/order/service/order/OrderService.java
  src/main/java/com/jamjam/bookjeok/domains/order/service/order/OrderServiceImpl.java
  src/main/java/com/jamjam/bookjeok/domains/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/com/jamjam/bookjeok/domains/payment/service/PaymentServiceImpl.java
Labels: ♻️ 리팩토링
